#!/bin/bash
git clone "https://github.com/Devil666face/ChatGPTosBot.git"
./venv/bin/pip install -r ChatGPTosBot/requirements.txt
./venv/bin/python -m nuitka --standalone --onefile --follow-imports ChatGPTosBot/main.py
mv main.bin compile/
# ./venv/bin/python -m nuitka --standalone --onefile --follow-imports ./venv/bin/sgpt
# rm -rf sgpt.build sgpt.dist sgpt.onefile-build
